winzou_state_machine:
    payment:
        class: App\Model\Payment
        property_path: state
        graph: payment
        states:
            new: ~
            pending: ~
            failed: ~
            paid: ~
            blocked: ~
        transitions:
            process:
                from: [new]
                to: pending
            fail:
                from: [pending]
                to: failed
            pay:
                from: [pending]
                to: paid
            block:
                from: [pending]
                to: blocked
        callbacks:
            before:
                reduce_amount:
                    on: ["pay"]
                    do: ["@App\\Operator\\InventoryOperator", "__invoke"]
                    args: ["object"]
            after:
                inform_about_payment:
                    on: ["pay"]
                    do: ["@App\\MessageDispatcher\\InformAboutPaidPayment", "__invoke"]
                    args: ["object"]
            guard:
                guard-blocked:
                    to: ["blocked"]
                    do: ["@App\\Authorizer\\BlockedAuthorizer", "__invoke"]
