framework:
    workflows:
        payment:
            type: 'state_machine'
            supports:
                - App\Model\Payment
            initial_marking: new
            marking_store:
                type: method
                property: state
            places:
                - new
                - pending
                - failed
                - paid
                - blocked
            transitions:
                process:
                    from: new
                    to: pending
                fail:
                    from: pending
                    to: failed
                pay:
                    from: pending
                    to: paid
                block:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: pending
                    to: blocked
